/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAdminRouteImport } from './routes/_site/admin'
import { Route as SiteAiRouteImport } from './routes/_site/ai'
import { Route as SiteAlertsRouteImport } from './routes/_site/alerts'
import { Route as SiteConverterRouteImport } from './routes/_site/converter'
import { Route as SiteExchangesRouteImport } from './routes/_site/exchanges'
import { Route as SiteNewsRouteImport } from './routes/_site/news'
import { Route as SitePortfolioRouteImport } from './routes/_site/portfolio'
import { Route as SitePricingRouteImport } from './routes/_site/pricing'
import { Route as SiteScreenerRouteImport } from './routes/_site/screener'
import { Route as SiteSignalsRouteImport } from './routes/_site/signals'
import { Route as SiteTrustRouteImport } from './routes/_site/trust'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as SiteCoinsIdRouteImport } from './routes/_site/coins/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBillingDodoRouteImport } from './routes/api/billing/dodo'
import { Route as ApiBillingNowpaymentsRouteImport } from './routes/api/billing/nowpayments'
import { Route as ApiBillingStripeRouteImport } from './routes/api/billing/stripe'
import { Route as ApiCronAlertsRouteImport } from './routes/api/cron/alerts'
import { Route as ApiMarketGlobalRouteImport } from './routes/api/market/global'
import { Route as ApiMarketListingRouteImport } from './routes/api/market/listing'
import { Route as ApiMarketSearchRouteImport } from './routes/api/market/search'
import { Route as ApiMarketTrendingRouteImport } from './routes/api/market/trending'
import { Route as ApiMarketCoinIdRouteImport } from './routes/api/market/coin.$id'
import { Route as ApiMarketHistoryIdRouteImport } from './routes/api/market/history.$id'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAdminRoute = SiteAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAiRoute = SiteAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAlertsRoute = SiteAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => SiteRoute,
} as any)
const SiteConverterRoute = SiteConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExchangesRoute = SiteExchangesRouteImport.update({
  id: '/exchanges',
  path: '/exchanges',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNewsRoute = SiteNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => SiteRoute,
} as any)
const SitePortfolioRoute = SitePortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => SiteRoute,
} as any)
const SitePricingRoute = SitePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => SiteRoute,
} as any)
const SiteScreenerRoute = SiteScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSignalsRoute = SiteSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrustRoute = SiteTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => SiteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteCoinsIdRoute = SiteCoinsIdRouteImport.update({
  id: '/coins/$id',
  path: '/coins/$id',
  getParentRoute: () => SiteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingDodoRoute = ApiBillingDodoRouteImport.update({
  id: '/api/billing/dodo',
  path: '/api/billing/dodo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingNowpaymentsRoute = ApiBillingNowpaymentsRouteImport.update({
  id: '/api/billing/nowpayments',
  path: '/api/billing/nowpayments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingStripeRoute = ApiBillingStripeRouteImport.update({
  id: '/api/billing/stripe',
  path: '/api/billing/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAlertsRoute = ApiCronAlertsRouteImport.update({
  id: '/api/cron/alerts',
  path: '/api/cron/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketGlobalRoute = ApiMarketGlobalRouteImport.update({
  id: '/api/market/global',
  path: '/api/market/global',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketListingRoute = ApiMarketListingRouteImport.update({
  id: '/api/market/listing',
  path: '/api/market/listing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketSearchRoute = ApiMarketSearchRouteImport.update({
  id: '/api/market/search',
  path: '/api/market/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketTrendingRoute = ApiMarketTrendingRouteImport.update({
  id: '/api/market/trending',
  path: '/api/market/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketCoinIdRoute = ApiMarketCoinIdRouteImport.update({
  id: '/api/market/coin/$id',
  path: '/api/market/coin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketHistoryIdRoute = ApiMarketHistoryIdRouteImport.update({
  id: '/api/market/history/$id',
  path: '/api/market/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof SiteAdminRoute
  '/ai': typeof SiteAiRoute
  '/alerts': typeof SiteAlertsRoute
  '/converter': typeof SiteConverterRoute
  '/exchanges': typeof SiteExchangesRoute
  '/news': typeof SiteNewsRoute
  '/portfolio': typeof SitePortfolioRoute
  '/pricing': typeof SitePricingRoute
  '/screener': typeof SiteScreenerRoute
  '/signals': typeof SiteSignalsRoute
  '/trust': typeof SiteTrustRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/coins/$id': typeof SiteCoinsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/dodo': typeof ApiBillingDodoRoute
  '/api/billing/nowpayments': typeof ApiBillingNowpaymentsRoute
  '/api/billing/stripe': typeof ApiBillingStripeRoute
  '/api/cron/alerts': typeof ApiCronAlertsRoute
  '/api/market/global': typeof ApiMarketGlobalRoute
  '/api/market/listing': typeof ApiMarketListingRoute
  '/api/market/search': typeof ApiMarketSearchRoute
  '/api/market/trending': typeof ApiMarketTrendingRoute
  '/api/market/coin/$id': typeof ApiMarketCoinIdRoute
  '/api/market/history/$id': typeof ApiMarketHistoryIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof SiteAdminRoute
  '/ai': typeof SiteAiRoute
  '/alerts': typeof SiteAlertsRoute
  '/converter': typeof SiteConverterRoute
  '/exchanges': typeof SiteExchangesRoute
  '/news': typeof SiteNewsRoute
  '/portfolio': typeof SitePortfolioRoute
  '/pricing': typeof SitePricingRoute
  '/screener': typeof SiteScreenerRoute
  '/signals': typeof SiteSignalsRoute
  '/trust': typeof SiteTrustRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/': typeof SiteIndexRoute
  '/coins/$id': typeof SiteCoinsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/dodo': typeof ApiBillingDodoRoute
  '/api/billing/nowpayments': typeof ApiBillingNowpaymentsRoute
  '/api/billing/stripe': typeof ApiBillingStripeRoute
  '/api/cron/alerts': typeof ApiCronAlertsRoute
  '/api/market/global': typeof ApiMarketGlobalRoute
  '/api/market/listing': typeof ApiMarketListingRoute
  '/api/market/search': typeof ApiMarketSearchRoute
  '/api/market/trending': typeof ApiMarketTrendingRoute
  '/api/market/coin/$id': typeof ApiMarketCoinIdRoute
  '/api/market/history/$id': typeof ApiMarketHistoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/admin': typeof SiteAdminRoute
  '/_site/ai': typeof SiteAiRoute
  '/_site/alerts': typeof SiteAlertsRoute
  '/_site/converter': typeof SiteConverterRoute
  '/_site/exchanges': typeof SiteExchangesRoute
  '/_site/news': typeof SiteNewsRoute
  '/_site/portfolio': typeof SitePortfolioRoute
  '/_site/pricing': typeof SitePricingRoute
  '/_site/screener': typeof SiteScreenerRoute
  '/_site/signals': typeof SiteSignalsRoute
  '/_site/trust': typeof SiteTrustRoute
  '/api/health': typeof ApiHealthRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/coins/$id': typeof SiteCoinsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/dodo': typeof ApiBillingDodoRoute
  '/api/billing/nowpayments': typeof ApiBillingNowpaymentsRoute
  '/api/billing/stripe': typeof ApiBillingStripeRoute
  '/api/cron/alerts': typeof ApiCronAlertsRoute
  '/api/market/global': typeof ApiMarketGlobalRoute
  '/api/market/listing': typeof ApiMarketListingRoute
  '/api/market/search': typeof ApiMarketSearchRoute
  '/api/market/trending': typeof ApiMarketTrendingRoute
  '/api/market/coin/$id': typeof ApiMarketCoinIdRoute
  '/api/market/history/$id': typeof ApiMarketHistoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/ai'
    | '/alerts'
    | '/converter'
    | '/exchanges'
    | '/news'
    | '/portfolio'
    | '/pricing'
    | '/screener'
    | '/signals'
    | '/trust'
    | '/api/health'
    | '/api/telegram'
    | '/coins/$id'
    | '/api/auth/$'
    | '/api/billing/dodo'
    | '/api/billing/nowpayments'
    | '/api/billing/stripe'
    | '/api/cron/alerts'
    | '/api/market/global'
    | '/api/market/listing'
    | '/api/market/search'
    | '/api/market/trending'
    | '/api/market/coin/$id'
    | '/api/market/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/ai'
    | '/alerts'
    | '/converter'
    | '/exchanges'
    | '/news'
    | '/portfolio'
    | '/pricing'
    | '/screener'
    | '/signals'
    | '/trust'
    | '/api/health'
    | '/api/telegram'
    | '/'
    | '/coins/$id'
    | '/api/auth/$'
    | '/api/billing/dodo'
    | '/api/billing/nowpayments'
    | '/api/billing/stripe'
    | '/api/cron/alerts'
    | '/api/market/global'
    | '/api/market/listing'
    | '/api/market/search'
    | '/api/market/trending'
    | '/api/market/coin/$id'
    | '/api/market/history/$id'
  id:
    | '__root__'
    | '/_site'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_site/admin'
    | '/_site/ai'
    | '/_site/alerts'
    | '/_site/converter'
    | '/_site/exchanges'
    | '/_site/news'
    | '/_site/portfolio'
    | '/_site/pricing'
    | '/_site/screener'
    | '/_site/signals'
    | '/_site/trust'
    | '/api/health'
    | '/api/telegram'
    | '/_site/'
    | '/_site/coins/$id'
    | '/api/auth/$'
    | '/api/billing/dodo'
    | '/api/billing/nowpayments'
    | '/api/billing/stripe'
    | '/api/cron/alerts'
    | '/api/market/global'
    | '/api/market/listing'
    | '/api/market/search'
    | '/api/market/trending'
    | '/api/market/coin/$id'
    | '/api/market/history/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingDodoRoute: typeof ApiBillingDodoRoute
  ApiBillingNowpaymentsRoute: typeof ApiBillingNowpaymentsRoute
  ApiBillingStripeRoute: typeof ApiBillingStripeRoute
  ApiCronAlertsRoute: typeof ApiCronAlertsRoute
  ApiMarketGlobalRoute: typeof ApiMarketGlobalRoute
  ApiMarketListingRoute: typeof ApiMarketListingRoute
  ApiMarketSearchRoute: typeof ApiMarketSearchRoute
  ApiMarketTrendingRoute: typeof ApiMarketTrendingRoute
  ApiMarketCoinIdRoute: typeof ApiMarketCoinIdRoute
  ApiMarketHistoryIdRoute: typeof ApiMarketHistoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/admin': {
      id: '/_site/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof SiteAdminRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ai': {
      id: '/_site/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof SiteAiRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/alerts': {
      id: '/_site/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof SiteAlertsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/converter': {
      id: '/_site/converter'
      path: '/converter'
      fullPath: '/converter'
      preLoaderRoute: typeof SiteConverterRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/exchanges': {
      id: '/_site/exchanges'
      path: '/exchanges'
      fullPath: '/exchanges'
      preLoaderRoute: typeof SiteExchangesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/news': {
      id: '/_site/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof SiteNewsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/portfolio': {
      id: '/_site/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof SitePortfolioRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/pricing': {
      id: '/_site/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof SitePricingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/screener': {
      id: '/_site/screener'
      path: '/screener'
      fullPath: '/screener'
      preLoaderRoute: typeof SiteScreenerRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/signals': {
      id: '/_site/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SiteSignalsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/trust': {
      id: '/_site/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof SiteTrustRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/coins/$id': {
      id: '/_site/coins/$id'
      path: '/coins/$id'
      fullPath: '/coins/$id'
      preLoaderRoute: typeof SiteCoinsIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/dodo': {
      id: '/api/billing/dodo'
      path: '/api/billing/dodo'
      fullPath: '/api/billing/dodo'
      preLoaderRoute: typeof ApiBillingDodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/nowpayments': {
      id: '/api/billing/nowpayments'
      path: '/api/billing/nowpayments'
      fullPath: '/api/billing/nowpayments'
      preLoaderRoute: typeof ApiBillingNowpaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/stripe': {
      id: '/api/billing/stripe'
      path: '/api/billing/stripe'
      fullPath: '/api/billing/stripe'
      preLoaderRoute: typeof ApiBillingStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/alerts': {
      id: '/api/cron/alerts'
      path: '/api/cron/alerts'
      fullPath: '/api/cron/alerts'
      preLoaderRoute: typeof ApiCronAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/global': {
      id: '/api/market/global'
      path: '/api/market/global'
      fullPath: '/api/market/global'
      preLoaderRoute: typeof ApiMarketGlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/listing': {
      id: '/api/market/listing'
      path: '/api/market/listing'
      fullPath: '/api/market/listing'
      preLoaderRoute: typeof ApiMarketListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/search': {
      id: '/api/market/search'
      path: '/api/market/search'
      fullPath: '/api/market/search'
      preLoaderRoute: typeof ApiMarketSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/trending': {
      id: '/api/market/trending'
      path: '/api/market/trending'
      fullPath: '/api/market/trending'
      preLoaderRoute: typeof ApiMarketTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/coin/$id': {
      id: '/api/market/coin/$id'
      path: '/api/market/coin/$id'
      fullPath: '/api/market/coin/$id'
      preLoaderRoute: typeof ApiMarketCoinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/market/history/$id': {
      id: '/api/market/history/$id'
      path: '/api/market/history/$id'
      fullPath: '/api/market/history/$id'
      preLoaderRoute: typeof ApiMarketHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteChildren {
  SiteAdminRoute: typeof SiteAdminRoute
  SiteAiRoute: typeof SiteAiRoute
  SiteAlertsRoute: typeof SiteAlertsRoute
  SiteConverterRoute: typeof SiteConverterRoute
  SiteExchangesRoute: typeof SiteExchangesRoute
  SiteNewsRoute: typeof SiteNewsRoute
  SitePortfolioRoute: typeof SitePortfolioRoute
  SitePricingRoute: typeof SitePricingRoute
  SiteScreenerRoute: typeof SiteScreenerRoute
  SiteSignalsRoute: typeof SiteSignalsRoute
  SiteTrustRoute: typeof SiteTrustRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteCoinsIdRoute: typeof SiteCoinsIdRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAdminRoute: SiteAdminRoute,
  SiteAiRoute: SiteAiRoute,
  SiteAlertsRoute: SiteAlertsRoute,
  SiteConverterRoute: SiteConverterRoute,
  SiteExchangesRoute: SiteExchangesRoute,
  SiteNewsRoute: SiteNewsRoute,
  SitePortfolioRoute: SitePortfolioRoute,
  SitePricingRoute: SitePricingRoute,
  SiteScreenerRoute: SiteScreenerRoute,
  SiteSignalsRoute: SiteSignalsRoute,
  SiteTrustRoute: SiteTrustRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteCoinsIdRoute: SiteCoinsIdRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingDodoRoute: ApiBillingDodoRoute,
  ApiBillingNowpaymentsRoute: ApiBillingNowpaymentsRoute,
  ApiBillingStripeRoute: ApiBillingStripeRoute,
  ApiCronAlertsRoute: ApiCronAlertsRoute,
  ApiMarketGlobalRoute: ApiMarketGlobalRoute,
  ApiMarketListingRoute: ApiMarketListingRoute,
  ApiMarketSearchRoute: ApiMarketSearchRoute,
  ApiMarketTrendingRoute: ApiMarketTrendingRoute,
  ApiMarketCoinIdRoute: ApiMarketCoinIdRoute,
  ApiMarketHistoryIdRoute: ApiMarketHistoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
